# Generated by Django 3.0.2 on 2021-02-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('works', models.CharField(max_length=255, verbose_name='Область деятельности')),
                ('ava', models.CharField(max_length=255, verbose_name='Src Аватарка')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='cli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ClientLK', verbose_name='Лот'),
        ),
    ]
