# Generated by Django 3.0.2 on 2021-02-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210212_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Участие в лоте', 'verbose_name_plural': 'Участие в лоте'},
        ),
        migrations.AlterModelOptions(
            name='clientlk',
            options={'ordering': ['name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='client',
            name='cli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ClientLK', verbose_name='Клиент'),
        ),
    ]
