# Generated by Django 3.0.2 on 2021-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210212_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Участие в лоте', 'verbose_name_plural': 'Участие в лоте'},
        ),
        migrations.AlterField(
            model_name='client',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлен в'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
