# Generated by Django 3.0.2 on 2021-02-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210212_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
